name: Build, Test and Deploy App

on:
  push:
  pull_request:

jobs:
  build-and-deploy:
    name: Test, Build And Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - uses: actions/setup-node@v1.4.0
        with:
          node-version: 12.x

      - name: Dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: UI tests
        run: |
          yarn build-storybook
          yarn percy exec -- cypress run
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Build
        if: github.ref == 'refs/heads/master'
        run: |
          yarn build
          yarn build-storybook

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        continue-on-error: true
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: storybook-static
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Deploy to NPM
        if: github.ref == 'refs/heads/master'
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
